# Generated by Django 4.0.1 on 2022-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_text_response', models.CharField(blank=True, choices=[('CONTENT', 'Content Team'), ('WEBD', 'Web Development'), ('VIDEO', 'Video Editing'), ('GD', 'Graphic Designing')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_text_response', models.CharField(blank=True, max_length=1000)),
                ('question_choices', models.CharField(blank=True, choices=[('CONTENT', 'Content Team'), ('WEBD', 'Web Development'), ('VIDEO', 'Video Editing'), ('GD', 'Graphic Designing')], max_length=7)),
            ],
        ),
    ]
